config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations], path: 'admins'
  devise_for :developers, path: 'developers', controllers: { registrations: :registrations }
  devise_for :recruiters, path: 'recruiters'

  root 'pages#home'
  get "/pages/:page", to: "pages#show", as: :pages
  get "jobsamples", to: "pages#jobsamples", as: :jobsamples

  resources :companies, only: [:new, :create, :edit, :update] do
    collection do
      get 'dashboard'
    end
  end

  resources :subscribers
  post '/stripe/webhooks', to: "stripe#webhooks"

  resources :developers do
    collection do
      get 'add_skills'
      get 'edit_profile'
      get 'dashboard'
    end
  end

  resources :jobs do
    resources :applications, only: [:new, :create, :show] do
      member do
        post 'contact'
        post 'reject'
      end
    end
    member do
      get 'skills'
      get 'benefits'
    end
  end


  authenticate :admin do
    namespace :admin do
      root 'dashboard#index'
      resources :dashboard, only: :index
      resources :competences
      resources :benefits
      resources :cultures
      resources :companies
      resources :recruiters
      resources :jobs
      resources :developers
      resources :applications, only: [:index, :show]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :developers, only: [:create] do
      resources :skills, only: [:index, :create]
    end
    resources :jobs, only: [:create] do
      resources :skills, only: [:index, :create]
    end
  end
  delete "/api/developers/:developer_id/skills/:name", to: "api/skills#destroy"
  delete "/api/jobs/:job_id/skills/:name", to: "api/skills#destroy"

end

app/models/application.rb
class Application < ApplicationRecord
  enum status: [ :pending, :opened, :contacted, :rejected ]

  belongs_to :match
  has_one :developer, through: :matches
  has_one :job, through: :matches
  has_one :company, through: :job
  validates :message, length: { maximum: 8000 }

  scope :open, -> { where.not(status: :rejected) }

end

app/controllers/admin/applications_controller.rb
class Admin::ApplicationsController < Admin::BaseController
  before_action :set_application, only: [:show]

  def index
    @applications = Application.all.order(created_at: :desc)
  end

  def show
    @job = @application.match.job
    @developer = @application.match.developer
  end

  private

  def set_application
    @application = Application.all.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


protected

  def after_sign_in_path_for(resource)
    if resource.class == Developer and disallowed_ip_location
      raise ActionController::RoutingError.new('Not Found')
    end

    if resource.class == Recruiter && resource.company.nil?
      new_company_path
    elsif resource.class == Recruiter
      dashboard_companies_path
    elsif resource.class == Developer && resource.sign_in_count == 1
      edit_profile_developers_path
    elsif resource.class == Developer
      dashboard_developers_path
    elsif resource.class == Admin
      request.env['omniauth.origin'] || stored_location_for(resource) || admin_dashboard_index_path
    else
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
  end

  def disallowed_ip_location
    return false unless Rails.env.production?
    country = session[:country] || (session[:country] = lookup_country)
    country.present? and not country.in? allowed_countries
  end

  def lookup_country
    ip = request.remote_ip
    response = Net::HTTP.get_response URI.parse "http://ipinfo.io/#{ip}/country"
    if response.code == '200'
      response.body.strip rescue ''
    end
  end

  def allowed_countries
    ENV['ALLOWED_COUNTRIES'].split(',') rescue ['US', 'ID']
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_developer!, only:[:new, :create]
  before_action :authenticate_recruiter!, only:[:show, :contact]
  before_action :set_application, only: [:show, :contact, :reject]
  before_action :set_job, only: [:new, :create, :reject]
  before_action :set_match, only: [:new, :create]

  def show
    DeveloperMailer.application_opened(@application).deliver if @application.pending?
    set_opened(@application)
  end

  def new
    @application = Application.new
    @developer = current_developer
    set_match
    @is_posted = application_is_posted?(@match)
    @applications_sent = applications_sent_today
    @recruiter = @job.vetted ? 'Find My Flock' : @job.company.name
  end

  def create
    @application = Application.new(application_params)
    @application.match = @match
    @developer = @match.developer
    @company = @match.job.company
    @mail_addresses = @company.recruiters_mail.join(",")

    attach_resumes(params[:application][:developer][:resumes],  @developer) if !params[:application][:developer].nil?

    if !@developer.resumes.attached?
      redirect_to new_job_application_path(@job), alert: "You need to upload a resume in order to apply."  and return
    end

    respond_to do |format|
      if @application.save
        format.html { redirect_to new_job_application_path(@match.job) }
        CompanyMailer.new_application_advise(@mail_addresses, @match, @developer).deliver
      else
        format.html { render :new, alert: "Something went wrong please try again." }
      end
    end
  end

  def contact
    message = params[:private_message]
    if !message.empty?
      @mail_address = current_recruiter.email
      CompanyMailer.contact_developer(message, @application, @job, @developer, @mail_address).deliver
      @application.contacted!
      redirect_to job_application_path(@job), notice: "We've sent an email to the candidate."
    end
  end

  def reject
    @application.rejected!
    DeveloperMailer.application_rejected(@application).deliver if @application.rejected?
    redirect_to dashboard_companies_path, notice: "We've sent an email to the candidate."
  end

  private

  def applications_sent_today
    count = 0
    matches = Match.where(developer: current_developer)
    matches.each do |match|
      application = Application.where(match: match, created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
      count += 1 if !application.empty?
    end
    count
  end

  def attach_resumes(resumes, developer)
    if resumes.any?
      developer.resumes.attach(resumes)
    end
  end

  def set_job
    @job = Job.find(params[:job_id])
  end

  def set_application
    @application = Application.find(params[:id])
    @job = @application.match.job
    @developer = @application.match.developer
  end

  def application_is_posted?(match)
    Application.where(match: match).any?
  end

  def set_match
    @match = Match.where(developer:current_developer, job:@job).first_or_create
    if current_developer.matched_job.include?(@job)
      @match
    else
      redirect_to dashboard_developers_path, notice: "Sorry you can't apply to this job!"
    end
  end

  def set_opened(application)
    if application.pending?
      application.opened!
    end
  end

  def application_params
    params.require(:application).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/_card.html.erb
<div class="row centered matched-job">

  <div class="col-xs-12 col-sm-12 col-md-2">
    <img class="job-avatar" src="/assets/jordan_fmf-72137f7c9425cf86f10b757071c5bf8cb3446080bbfd6dbfcbe01cb23edab0aa.jpg" alt="Jordan fmf">
    <p class="pt-2" style="margin-bottom:0;">Jordan Camelia</p>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-4 matched-job-title matched-job-skills matched-job-separator">
    <h5 class="row matched-job-skills-title">Matched job</h5>
    <h4><%= job.title %></h4>
    <h5 class="text-muted">Denver</h5>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-4 matched-job-skills">
    <h5 class="row matched-job-skills-title">Matching skills</h5>
    <div class="row">
      <table class="table">
        <tbody>
          <tr>
            <td>Javascript</td>
            <td>4</td>
          </tr>
          <tr>
            <td>CSS</td>
            <td>3</td>
          </tr>
          <tr>
            <td>Rails</td>
            <td>1</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-2 col-md-2">
    <button class="btn-orange btn-apply">View</button>
  </div>

</div>

app/views/applications/new.html.erb
<div class="container-fluid user-job-show-container">

  <div class="row">

    <div class="col-sm-12 col-md-6 job-details-container">
      <%= render 'jobs/full_job' %>
    </div>

    <div class="col-sm-12 col-md-6 job-application-container">
      <% if !@is_posted %>
        <div class="job-show-titles mb-4">
          <h4 class="row justify-content-center underlined">Apply to this job</h4>
        </div>

        <% if (!@applications_sent.nil? && @applications_sent >= 5) %>

          <p class="alert pt-3 pb-3" role="alert" style="color: gray;">
            <i class="fas fa-exclamation-triangle fa-2x fa-pull-left fa-border"></i> You have reached the maximum number of applications per day <br/ >(5 per day).
          </p>
        <% else %>
        <%= simple_form_for([@job, @application]) do |f| %>
          <%= f.input :message,  :input_html => {:rows => 5}, label: "Write a message to the recruiter at #{@recruiter}", required: true %>

          <% if !@developer.resumes.attached? %>
            <%= f.simple_fields_for @developer do |f| %>
              <%= f.input :resumes, as: :file, :input_html => {multiple: true , :data => {"direct-upload-url": "#{root_url}rails/active_storage/direct_uploads" }, accept: "application/pdf" } %>
            <% end  %>
          <% else %>
            <p class="alert pt-3 pb-3" role="alert" style="color: gray;">
              <i class="fas fa-quote-left fa-2x fa-pull-left fa-border"></i> We will attach the resume uploaded on your profile with this request.
            </p>
          <% end  %>

            <%= f.submit "Send application", class: "btn btn-orange btn-application btn-block" %>
          <% end %>
        <% end %>



         <% else %>

          <div class="job-show-titles">
            <h4 class="row justify-content-center underlined">Application sent</h4>
          </div>

          <div class="applied-message">
            <h5 class="h6 centered">Congratulations!</h5>
            <p>Your application has beeing sent and will be reviewed by the recruiters at <%= @job.company.name %>.</p>
            <p>At this time, you can check your application status on your dashboard under the “Applications” tab.</p>
          </div>

       <% end %>

    </div>

  </div>

  <div class="centered my-5">
    <%= link_to "< Back", dashboard_developers_path(@developer), class: "btn-orange btn-back"  %>
  </div>
</div>

app/views/applications/show.html.erb
<div class="container-fluid company-job-matched-container">
  <div class="row">
    <!-- user details -->
    <div class="col-sm-12 col-md-6 user-details-container">

      <div class="user-show-titles">
        <h4 class="row justify-content-center underlined-orange-dark" style=>Candidate</h4>
      </div>

      <div class="user-intro mx-auto">
        <div class="avatar">
          <%= image_tag @developer.avatar_thumbnail, class: "d-block mx-auto" %>
        </div>
        <div class="user-info">
          <h5 class="pt-3"><%= @developer.full_name %></h5>
          <% if @developer.github_url? %>
          <a href="<%= @developer.github_url %>" target="_blank">
            <i class="fab fa-github fa-2x" style="color: #24292e; text-decoration: none; margin-right: 1vh; margin-left: 1vh;"></i></a>
            <% end %>

            <% if @developer.linkedin_url? %>
            <a href="<%= @developer.linkedin_url %>" target="_blank">
              <i class="fab fa-linkedin fa-2x" style="color: #0073b1; text-decoration: none; margin-right: 1vh; margin-left: 1vh;"></i></a>
              <% end %>
              <h6 class="pt-3">Current location: <br /></h6>
              <p><%= @developer.city %>, <%= @developer.country %></p>
            </div>
          </div>

          <div class="user-matched-skills centered mx-auto">

            <div class="row" style="padding-right: 12px; padding-left: 12px;">
              <div class="col-md-12 col-lg-6">
                <div class="user-show-titles">
                  <h5 class="h6 underlined-top-orange pt-3 mt-4"><%= @developer.first_name %>'s skills</h5>
                </div>
                <div style="max-width: 330px; margin: auto;">
                  <%= render "developers/shared/skills_table" %>
                </div>
              </div>

              <div class="col-md-12 col-lg-6">
                <div class="user-show-titles">
                  <h5 class="h6 underlined-top-orange pt-3 mt-4">Your job's skills</h5>
                </div>
                <div style="max-width: 330px; margin: auto;">
                  <%= render "jobs/shared/skills_table", skills: @job.skills %>
                </div>

              </div>
            </div>
          </div>
        </div>



      <!-- Application -->
      <div class="col-sm-12 col-md-6 job-application-container">
        <div class="user-show-titles">
         <h4 class="row justify-content-center underlined">Application</h4>
       </div>
       <h6 class="text-muted centered" style="font-size: 15px;"><%= @job.title %></h6>
       <h5 class="matched-job-skills-title centered pt-4">Current state</h5>
       <div class="application-buttons mx-auto" style= "max-width: 100px;">
        <% if @application.status == "contacted" %>
        <div class="badge btn-contacted">Contacted</div>
        <% elsif @application.status == "opened" %>
        <div class="badge btn-opened">Opened</div>
        <% elsif @application.status == "rejected" %>
        <div class="badge btn-pending">Rejected</div>
        <% else %>
        <div class="badge btn-pending">New</div>
        <% end %>
      </div>


      <% if @application.status != "rejected" %>
        <div class="row">
          <div class="col-md-12 pt-4">
            <h4 class='h6'>Message from <%= @developer.first_name %></h4>
            <p><%= @application.message %></p>
          </div>
        </div>

        <% if current_recruiter.company.is_allowed_member %>
          <div class="row pt-4 pb-4">
            <div class="col-xs-12 col-sm-12 centered">
              <h4 class='h6'>Resume</h4>
              <% @developer.resumes.each do |resume| %>
              <%= link_to "Download", rails_blob_path(resume, disposition: "attachment"), class: "btn btn-orange btn-application-small", style: "padding-top: 6px;" %>
              <% end %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="user-show-titles">
                <h5 class="h6 justify-content-center underlined-top-orange mb-0 pb-0 pt-3"></h5>
              </div>
              <h4 class='h6'>Contact <%= @developer.first_name %> by email</h4>

              <%= simple_form_for :application,  url: contact_job_application_path(@job), method: :post do |f| %>
                <div class="form-group">
                  <textarea rows="4" cols="50" name="private_message" class="input-group" placeholder="Type your personal message for the candidate" required></textarea>
                </div>
                <div class="centered">
                  <%= f.submit 'Send email', class: "btn btn-orange btn-application" %>
                </div>
              <% end %>
            </div>
          </div>

          <div class="row mt-5">
            <h4 class='h6'>Reject this application</h4>
            <p>In case the candidate do not match with your needs please reject the application request.</p>
            <%= link_to "Reject application", reject_job_application_path(@job), method: :post, class: "btn btn-danger", :data => {:confirm => 'Are you sure?'} %>
          </div>
        <% else %>
          <div class="alert alert-info mt-5">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <i class="fas fa-exclamation-triangle fa-3x fa-pull-left fa-border fa-border-info"></i>
            <p><strong>We’re happy to see that you have interest in a job from a qualified developer!</strong><br>In order to review their application materials and contact them, please <%= link_to "Become a member", pages_path(:pricing) %> once again.</p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

<div class="centered my-5">
  <%= link_to "< Back", dashboard_companies_path(@company), class: "btn-orange btn-back"  %>
</div>
</div>