config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations], path: 'admins'
  devise_for :developers, path: 'developers', controllers: { registrations: :registrations }
  devise_for :recruiters, path: 'recruiters'

  root 'pages#home'
  get "/pages/:page", to: "pages#show", as: :pages
  get "jobsamples", to: "pages#jobsamples", as: :jobsamples

  resources :companies, only: [:new, :create, :edit, :update] do
    collection do
      get 'dashboard'
    end
  end

  resources :subscribers
  post '/stripe/webhooks', to: "stripe#webhooks"

  resources :developers do
    collection do
      get 'add_skills'
      get 'edit_profile'
      get 'dashboard'
    end
  end

  resources :jobs do
    resources :applications, only: [:new, :create, :show] do
      member do
        post 'contact'
        post 'reject'
      end
    end
    member do
      get 'skills'
      get 'benefits'
    end
  end


  authenticate :admin do
    namespace :admin do
      root 'dashboard#index'
      resources :dashboard, only: :index
      resources :competences
      resources :benefits
      resources :cultures
      resources :companies
      resources :recruiters
      resources :jobs
      resources :developers
      resources :applications, only: [:index, :show]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :developers, only: [:create] do
      resources :skills, only: [:index, :create]
    end
    resources :jobs, only: [:create] do
      resources :skills, only: [:index, :create]
    end
  end
  delete "/api/developers/:developer_id/skills/:name", to: "api/skills#destroy"
  delete "/api/jobs/:job_id/skills/:name", to: "api/skills#destroy"

end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs, dependent: :destroy
  has_many :recruiters, dependent: :nullify
  has_many_attached :images
  has_one :subscriber, -> { order created_at: :desc }, dependent: :destroy

  validates :name, :url, presence: true,  length: { maximum: 500 }

  def applications
    job_ids = jobs.pluck(:id)
    matches_ids = Match.where(job_id: job_ids).pluck(:id)
    Application.where(match_id: matches_ids)
  end

  def recruiters_mail
    self.recruiters.pluck(:email).flatten.uniq
  end

  def is_member?
    !subscriber.nil? && (subscriber.active? || (subscriber.canceled? && subscriber.subscription_expires_at >= Date.today) || subscriber.trialing? || subscriber.past_due?)
  end

  def is_allowed_member
    is_member? && (subscriber.plan.stripe_id == "1-job" && jobs.count < 1) ||
    is_member? && (subscriber.plan.stripe_id == "3-jobs" && jobs.count < 3) ||
    vetted?
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::BaseController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all.order(name: :asc)
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to admin_companies_path, notice: 'Company was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
    end
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name, :url, :industry, :vetted, images: [])
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_recruiter!, only: [:new, :create, :dashboard, :edit]
  before_action :set_company, only: [:dashboard, :edit, :update]

  def new
    is_recruiter_in_company?
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    #Set company to recruiter after creation
    set_company_to_main_recruiter

    respond_to do |format|
      if @company.save
        CompanyMailer.welcome_company(@company).deliver
        if @company.is_member?
          format.html { redirect_to dashboard_companies_path, notice: 'Welcome on board, add your first job!' }
        else
          format.html { redirect_to new_subscriber_path }
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to dashboard_companies_path, notice: 'Your company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def dashboard
    @company = current_recruiter.company
    if @company.nil?
      redirect_to new_company_path, alert: 'Please create your company' and return
    end
    @jobs = @company.jobs
  end

  private

  def set_company
    @company = current_recruiter.company
  end

  def set_company_to_main_recruiter
    current_recruiter.company = @company
    current_recruiter.main_recruiter = true
    current_recruiter.save
  end

  def is_recruiter_in_company?
    if !current_recruiter.company.nil?
      redirect_to dashboard_companies_path, notice: 'Already part of a company!'
    end
  end

  def company_params
    params.require(:company).permit(:name, :url, :industry, images: [])
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for company, url: url, action: :update, local: true do |form| %>
  <h5 class="mt-3">Basic</h5>
  <div class="form-row">
    <div class="col-12 col-md-6">
      <%= form.input :name %>
      <small class="form-text text-muted" style="margin:0;">We will only show the name to our candidate in case of 100% match.</small>
    </div>
    <div class="col-12 col-md-6">
      <%= form.input :industry %>
    </div>
  </div>
  <div class="form-row mt-3">
    <div class="col col-md-6">
      <%= form.input :url %>
    </div>
  </div>
  <h5 class="mt-5 my-3">Pictures</h5>
  <small class="form-text text-muted">Upload your company logo and office space to show what makes working at your company unique.</small>
  <br>
  <%= form.file_field :images, multiple: true, direct_upload: true, label:false, accept: "image/x-png,image/jpeg"  %>
  <br /><br />
  <div class="row">
    <div class="col-12">
      <p>You can view the pictures already uploaded:</p>
      <%= render "utils/carousel", images: @company.images %>
    </div>
  </div>

  <div class="text-center mt-3">
    <%= form.submit "Confirm", class: "btn btn-orange btn-application"  %>
  </div>
<% end %>

app/views/companies/dashboard.html.erb
<div class="container-fluid user-dashboard-container">
  <div id ="dashboard-container">
    <div class="row">

      <main role="main" class="col-md-12 pt-3 px-4 mx-auto" style="min-height:100vh; max-width: 880px;">

        <div class="dashboard-header">
          <div class="pb-2 mb-3" style="width: 100%">
            <h1 class="centered my-4" style="color: #b5b5b5;"><%= @company.name %></h1>
            <div class="pt-2 centered">
              <%= link_to image_tag('plus.png'), new_job_path, class: "btn-add-job" %> <%= link_to "Add a new job", new_job_path, style: "color: gray;" %>
            </div>
          </div>
        </div>

        <nav class="nav nav-pills flex-column flex-sm-row mb-4" id="nav-tab" role="tablist">
          <a class="flex-sm-fill text-sm-center nav-link nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="true">My Active Jobs</a>
          <a class="flex-sm-fill text-sm-center nav-link nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="false">Applications</a>
        </nav>

        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <div class="container matched-jobs" id="jobs-list">

              <% @company.applications.open.each_with_index do |application, index| %>

              <div class="row centered matched-job">

                <div class="col-xs-12 col-sm-12 col-md-2">
                  <%= image_tag application.match.developer.avatar, class: "job-avatar" if !application.match.developer.avatar.attachment.nil? %>
                  <p class="pt-2" style="margin-bottom:0;"><%= application.match.developer.first_name %> <%= application.match.developer.last_name %></p>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-4 matched-job-title matched-job-skills matched-job-separator">
                  <h5 class="row matched-job-skills-title">Matched job</h5>
                  <h4><%= application.match.job.title %></h4>
                  <h5 class="text-muted"><%= application.match.job.company.name  %></h5>
                  <p class="text-muted">
                    <%= application.match.job.city %>
                    <% if application.match.job.remote == ["remote"] %>
                    - Remote
                    <% elsif application.match.job.remote == ["office"] %>
                    - Office
                    <% elsif application.match.job.remote == ["remote", "office"]%>
                    - Office & Remote
                    <% end %>
                  </p>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-4 matched-job-skills">
                  <h5 class="row matched-job-skills-title">Matching skills</h5>
                  <div class="row">
                    <table class="table">
                      <tbody>
                        <% application.match.job.skills.each do |skill| %>
                        <tr>
                          <td><i class="devicon-<%= skill.name %>-plain colored"></i></td>
                          <td><%= skill.name %></td>
                          <td><%= skill.level %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-2">
                  <h5 class="matched-job-skills-title">Current state</h5>
                  <div class="application-buttons">
                    <% if application.status == "contacted" %>
                    <div class="badge btn-contacted">Contacted</div>
                    <% elsif application.status == "opened" %>
                    <div class="badge btn-opened">Opened</div>
                    <% elsif application.status == "rejected" %>
                    <div class="badge btn-pending">Rejected</div>
                    <% else %>
                    <div class="badge btn-pending">New</div>
                    <% end %>
                    <%= link_to "View", job_application_path(application.match.job, application), class:"btn-orange btn-apply" %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
          <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

            <% @jobs.each_with_index do |job| %>

            <div class="row centered matched-job">
              <div class="col-xs-11 col-sm-11 col-md-5">

                <h4><%= job.title %></h4>
                <h5 class="text-muted"><%= job.company.name  %></h5>
                <p class="text-muted">
                  <%= job.city %>
                  <% if job.remote == ["remote"] %>
                  - Remote
                  <% elsif job.remote == ["office"] %>
                  - Office
                  <% elsif job.remote == ["remote", "office"]%>
                  - Office & Remote
                  <% end %>
                </p>
              </div>

              <div class="col-xs-12 col-sm-12 col-md-5 matched-job-skills">
                <h5 class="row matched-job-skills-title">Skills</h5>
                <div class="row">
                  <table class="table">
                    <tbody>
                      <% job.skills.each do |skill| %>
                      <tr>
                        <td><i class="devicon-<%= skill.name %>-plain colored"></i></td>
                        <td><%= skill.name %></td>
                        <td><%= skill.level %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>


              <div class="col-xs-12 col-sm-12 col-md-2">
                <%= link_to "See", job_path(job), class: "btn btn-orange btn-see-job"  %>
                <%= link_to "Edit", edit_job_path(job), class: "btn btn-orange btn-edit-job"  %>
              </div>

            </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/edit.html.erb
<div class="container my-5">
  <div class="row justify-content-md-center">
    <div class="col col-md-8">
      <div class="card">
        <div class="card-body">
          <h2 class="text-center">Edit your company</h2>
          <%= render 'form', company: @company, url: company_path(@company) %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
Create a new company!
<h1>New company</h1>

<%= render 'form', company: @company, url: companies_path %>