config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations], path: 'admins'
  devise_for :developers, path: 'developers', controllers: { registrations: :registrations }
  devise_for :recruiters, path: 'recruiters'

  root 'pages#home'
  get "/pages/:page", to: "pages#show", as: :pages
  get "jobsamples", to: "pages#jobsamples", as: :jobsamples

  resources :companies, only: [:new, :create, :edit, :update] do
    collection do
      get 'dashboard'
    end
  end

  resources :subscribers
  post '/stripe/webhooks', to: "stripe#webhooks"

  resources :developers do
    collection do
      get 'add_skills'
      get 'edit_profile'
      get 'dashboard'
    end
  end

  resources :jobs do
    resources :applications, only: [:new, :create, :show] do
      member do
        post 'contact'
        post 'reject'
      end
    end
    member do
      get 'skills'
      get 'benefits'
    end
  end


  authenticate :admin do
    namespace :admin do
      root 'dashboard#index'
      resources :dashboard, only: :index
      resources :competences
      resources :benefits
      resources :cultures
      resources :companies
      resources :recruiters
      resources :jobs
      resources :developers
      resources :applications, only: [:index, :show]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :developers, only: [:create] do
      resources :skills, only: [:index, :create]
    end
    resources :jobs, only: [:create] do
      resources :skills, only: [:index, :create]
    end
  end
  delete "/api/developers/:developer_id/skills/:name", to: "api/skills#destroy"
  delete "/api/jobs/:job_id/skills/:name", to: "api/skills#destroy"

end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :confirmable
  before_validation :email_downcase
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validate :password_complexity
  belongs_to :company, optional: true

  def email_downcase
    email = email.strip.downcase if email
  end

  def password_complexity
    if !password.nil? && password !~ /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,}$/
      errors.add :password, 'Password must include at least one lowercase letter, one uppercase letter, and one digit'
    end
  end

  def skip_confirmation
    self.skip_confirmation!
  end

end

app/controllers/admin/recruiters_controller.rb
class Admin::RecruitersController < Admin::BaseController
  before_action :set_recruiter, only: %i[show edit update destroy]

  # GET /recruiters
  # GET /recruiters.json
  def index
    @recruiters = Recruiter.all
  end

  # GET /recruiter/1
  # GET /recruiter/1.json
  def show; end

  # GET /recruiter/new
  def new
    @recruiter = Recruiter.new
  end

  # GET /recruiter/1/edit
  def edit; end

  # POST /recruiter
  # POST /recruiter.json
  def create
    @recruiter = Recruiter.new(recruiter_params)
    @recruiter.skip_confirmation if admin_signed_in?
    respond_to do |format|
      if @recruiter.save
        format.html { redirect_to admin_recruiter_path(@recruiter), notice: 'Recruiter was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /recruiter/1
  # PATCH/PUT /recruiter/1.json
  def update
    respond_to do |format|
      if @recruiter.update(recruiter_params)
        format.html { redirect_to admin_recruiter_path(@recruiter), notice: 'Recruiter was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /recruiter/1
  # DELETE /recruiter/1.json
  def destroy
    @recruiter.destroy
    respond_to do |format|
      format.html { redirect_to admin_recruiters_url, notice: 'Recruiter was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recruiter
    @recruiter = Recruiter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.

  def recruiter_params
    params.require(:recruiter).permit(:email, :password, :password_confirmation, :company_id)
  end
end

app/views/recruiters/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive the confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/recruiters/shared/_tab_nav.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= active_link_to 'Log in as Company', new_recruiter_session_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= active_link_to 'Sign up as Company', new_recruiter_registration_path, class: "nav-link" %>
  </li>
</ul>