config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations], path: 'admins'
  devise_for :developers, path: 'developers', controllers: { registrations: :registrations }
  devise_for :recruiters, path: 'recruiters'

  root 'pages#home'
  get "/pages/:page", to: "pages#show", as: :pages
  get "jobsamples", to: "pages#jobsamples", as: :jobsamples

  resources :companies, only: [:new, :create, :edit, :update] do
    collection do
      get 'dashboard'
    end
  end

  resources :subscribers
  post '/stripe/webhooks', to: "stripe#webhooks"

  resources :developers do
    collection do
      get 'add_skills'
      get 'edit_profile'
      get 'dashboard'
    end
  end

  resources :jobs do
    resources :applications, only: [:new, :create, :show] do
      member do
        post 'contact'
        post 'reject'
      end
    end
    member do
      get 'skills'
      get 'benefits'
    end
  end


  authenticate :admin do
    namespace :admin do
      root 'dashboard#index'
      resources :dashboard, only: :index
      resources :competences
      resources :benefits
      resources :cultures
      resources :companies
      resources :recruiters
      resources :jobs
      resources :developers
      resources :applications, only: [:index, :show]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :developers, only: [:create] do
      resources :skills, only: [:index, :create]
    end
    resources :jobs, only: [:create] do
      resources :skills, only: [:index, :create]
    end
  end
  delete "/api/developers/:developer_id/skills/:name", to: "api/skills#destroy"
  delete "/api/jobs/:job_id/skills/:name", to: "api/skills#destroy"

end

app/views/shared/navbar/_basic-navbar.html.erb
<li class="nav-item active">
  <%= active_link_to 'Jobs', jobsamples_path, class: "nav-link" %>
</li>
<li class="nav-link d-none d-sm-block"> | </li>
<li class="nav-item">
  <%= active_link_to 'Developers ', new_developer_session_path, class: "nav-link", id: "NavEmployers" %>
</li>
<li class="nav-link d-none d-sm-block"> | </li>
<li class="nav-item">
  <%= active_link_to 'Employers', pages_path(:pricing), class: "nav-link", id: "NavEmployers" %>
</li>

app/views/shared/navbar/_company-navbar.html.erb
<li class="nav-item">
  <%= active_link_to "Dashboard", dashboard_companies_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <div class="avatar-navbar p-3">
  </div>
</li>
<li>
  <div class="dropdown">
    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-cog"></i>
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <h6 class="dropdown-header"><%= current_recruiter.email %></h6>
      <%= active_link_to "My Subscription", subscribers_path, class: "dropdown-item" if !current_recruiter.company.nil? && current_recruiter.company.is_member? %>
      <%= active_link_to "Edit Company", edit_company_path(current_recruiter.company), class: "dropdown-item" if !current_recruiter.company.nil? %>
      <%= active_link_to "Account Settings", edit_recruiter_registration_path, class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to 'Logout', destroy_recruiter_session_path, method: :delete , class: "dropdown-item" %>
    </div>
  </div>
</li>

app/views/shared/navbar/_developer-navbar.html.erb
<li class="nav-item">
  <%= active_link_to "Dashboard", dashboard_developers_path, class: "nav-link" %>
</li>
<li>
  <div class="dropdown">
    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-cog"></i>
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <h6 class="dropdown-header"><%= current_developer.email %></h6>
      <%= active_link_to "My Dev Profile", developer_path(current_developer), class: "dropdown-item" %>
      <%= active_link_to "Edit Your Profile", edit_profile_developers_path, class: "dropdown-item" %>
      <%= active_link_to "Manage Your Skills", add_skills_developers_path, class: "dropdown-item" %>
      <%= active_link_to "Account Settings", edit_developer_registration_path, class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to 'Logout', destroy_developer_session_path, method: :delete , class: "dropdown-item" %>
    </div>
  </div>
</li>

app/views/shared/navbar/_main-navbar.html.erb
<div class="navbar navbar-expand-md navbar-light fixed-top" id="NavContent" style="background-color: white;">

  <% if recruiter_signed_in? %>
    <%= link_to dashboard_companies_path, class: "nav-link" do %>
      <%= image_tag "flock_logo.png", class: "navbar-brand ml-auto", id: "Logo", alt: "Flock logo" %>
    <% end %>
  <% elsif developer_signed_in? %>
    <%= link_to dashboard_developers_path, class: "nav-link" do %>
      <%= image_tag "flock_logo.png", class: "navbar-brand ml-auto", id: "Logo", alt: "Flock logo" %>
    <% end %>
  <% else %>
    <%= link_to root_path do %>
      <%= image_tag "flock_logo.png", class: "navbar-brand ml-auto", id: "Logo", alt: "Flock logo" %>
    <% end %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end pr-4" id="navbarCollapse">
    <ul class="navbar-nav">
      <% if recruiter_signed_in? %>
        <%= render "shared/navbar/company-navbar" %>
      <% elsif developer_signed_in? %>
        <%= render "shared/navbar/developer-navbar" %>
      <% else %>
        <%= render "shared/navbar/basic-navbar" %>
      <% end %>
    </ul>
  </div>
</div>